version: "3.8"

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - realtimechat_redis
      - backend
      - frontend
    networks:
      - dev
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - realtimechat_redis
    networks:
      - dev
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - dev
  realtimechat_redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dev
